// <auto-generated />
using System;
using Infrastructure.Estadia.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Estadia.EF.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20221213181032_InitialStructure")]
    partial class InitialStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Estadia.EF.ReadModel.CheckinReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("checkinId");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clienteId");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HabitacionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("habitacionId");

                    b.Property<Guid>("HuespedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reservaId");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("HuespedId");

                    b.ToTable("Checkin", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Estadia.EF.ReadModel.CheckoutReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("checkoutId");

                    b.Property<Guid>("CheckinId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("checkinId");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clienteId");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("creditCardId");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CheckinId");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("PagoId");

                    b.ToTable("Checkout", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Estadia.EF.ReadModel.CreditCardReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("creditCardId");

                    b.Property<string>("NumeroTarjeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("numero_tarjeta");

                    b.Property<string>("TipoTarjeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo_tarjeta");

                    b.HasKey("Id");

                    b.ToTable("CreditCard", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Estadia.EF.ReadModel.FacturaReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("facturaId");

                    b.Property<string>("DetalleFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalle_factura");

                    b.Property<string>("FechaFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fecha_factura");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("Factura", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Estadia.EF.ReadModel.HabitacionReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("habitacionId");

                    b.Property<string>("CaracteristicasHabitacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("caracteristica_habitacion");

                    b.Property<string>("CodigoHabitacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codigo_habitacion");

                    b.Property<string>("Disponibilidad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("disponibilidad");

                    b.Property<int>("LimitePersona")
                        .HasColumnType("int")
                        .HasColumnName("limite_persona");

                    b.Property<int>("NumeroHabitacion")
                        .HasColumnType("int")
                        .HasColumnName("numero_habitacion");

                    b.Property<double>("PrecioHabitacion")
                        .HasColumnType("float")
                        .HasColumnName("precio_habitacion");

                    b.Property<Guid>("TipoHabitacion")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tipo_habitacion");

                    b.HasKey("Id");

                    b.ToTable("Habitacion", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Estadia.EF.ReadModel.HuespedReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("huespedId");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dni");

                    b.HasKey("Id");

                    b.ToTable("Huesped", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Estadia.EF.ReadModel.PagoReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pagoId");

                    b.Property<double>("Total")
                        .HasColumnType("float")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Estadia.EF.ReadModel.CheckinReadModel", b =>
                {
                    b.HasOne("Infrastructure.Estadia.EF.ReadModel.CreditCardReadModel", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Infrastructure.Estadia.EF.ReadModel.HabitacionReadModel", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Estadia.EF.ReadModel.HuespedReadModel", "Huesped")
                        .WithMany()
                        .HasForeignKey("HuespedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("Habitacion");

                    b.Navigation("Huesped");
                });

            modelBuilder.Entity("Infrastructure.Estadia.EF.ReadModel.CheckoutReadModel", b =>
                {
                    b.HasOne("Infrastructure.Estadia.EF.ReadModel.CheckinReadModel", "Checkin")
                        .WithMany()
                        .HasForeignKey("CheckinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Estadia.EF.ReadModel.CreditCardReadModel", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Estadia.EF.ReadModel.FacturaReadModel", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Infrastructure.Estadia.EF.ReadModel.PagoReadModel", "Pago")
                        .WithMany()
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Checkin");

                    b.Navigation("CreditCard");

                    b.Navigation("Factura");

                    b.Navigation("Pago");
                });
#pragma warning restore 612, 618
        }
    }
}
